=== Nana6660/Projet_DSB/Q7-DTD.dtd
<!ELEMENT cinema (documentation+,film)>
<!ATTLIST cinema idCinema ID #REQUIRED
nom CDATA #REQUIRED
adresse CDATA #REQUIRED>

<!ELEMENT documentation(#PCDATA|lien)>
<!ATTLIST documentation date Date #IMPLIED 
auteur CDATA #IMPLIED >
<!ELEMENT lien (#PCDATA)>

<!ELEMENT film (#PCDATA|documentation*) >
<!ATTLIST film idFilm ID #REQUIRED 
titre CDATA #REQUIRED 
dateDeSortie DATE #REQUIRED 
durÃ©e TIME #REQUIRED>

=== Nana6660/Projet_DSB/Q8b-XML.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<?xml-stylesheet href="10a-XML.css" type="text/css"?>
<!DOCTYPE cinema SYSTEM "Q7-DTD.dtd">
<cinema idCinema = "1" nom ="gaumont rennes" adresse="Gaumont Rennes, 12 Rue Yvonne Jean-Haffen" >
	<!-- ceci est un document xml -->
	<documentation>
		La partie MCD utilise MOCODO dont l’adresse est <lien>http ://mocodo.wingi.net/</lien>
        et une image se trouve ici <lien>image.png</lien>
	</documentation>
	<documentation>
		La partie MCD utilise MOCODO dont l’adresse est <lien>http ://mocodo.wingi.net/</lien>
        et une image se trouve ici <lien>image.png</lien>
	</documentation>
    <film idFilm = "2002"  titre ="Red Notice" dateDeSortie = "2021-12-11" duree= "1 heure 05" > 
     <documentation>
        La partie MCD utilise MOCODO dont l’adresse est <lien>http ://mocodo.wingi.net/</lien>
        et une image se trouve ici <lien>image.png</lien>
     </documentation>
    </film>
</cinema>
